subroutine write_dlfield   
    use modfim,only: n_mol
    use modnei,only: nbond,bond,n_ang,n_dih,angle,dihedral,mang,mdih
    use mode,  only: x!, a, b, c
    implicit none

    integer         i,j!, ti
    !integer         n_atom
    !integer         nw_bonds,nw_angles,nw_dihs
    real(8)      :: pi=3.1415926535897932
    real(8)      :: r0=1.4000
    real(8)      :: kj2ev=1.03643E-02
    real(8)         kc
    real(8)         kcth
    real(8)         thet
    real(8)         kdih
    real(8)         dih
    real(8)         r1(3),r2(3)
    !real(8)         r_a,r_b,r_c!,ina,inb,inc
    real(8)         rsq1,rsq2,radi
    real(8)         ang,cos_ang,ave_ang

    !real(8),allocatable:: nw_bond(:,:)


    call  neighbor
    call  findmole
!   call writeat
!  Determining Angles

    n_ang = 0
    !print *,nbond



    call angles

    print '(I5,A7)',n_ang,' angles'
!   Determining dihedrals
    
    call torsions


    open(31,file='FIELD.x',status='unknown')
    write(31,100)'Generated by Effective Material Design Kit'
    write(31,100)'(gfeng.alan@hotmail.com)'
    write(31,100)'units  eV'
    write(31,200)'nummols',n_mol
!    n_atom= 
!    write(31,200)'atoms',n_atom

    write(31,200)'bonds ',nbond

    kc=392459.2*kj2ev
    do i=1,nbond
       write(31,300)'harm  ',bond(1,i),bond(2,i),kc,r0
    enddo

    write(31,200)'angles',n_ang

    kcth = 544.184*kj2ev
    thet = 120.0

    open(32,file='angles.log',status='unknown')

    ave_ang = 0.0
    do i=1,n_ang
         !r_c = (a(1)*b(2)-a(2)*b(1))*(b(2)*delz-b(3)*dely) - (a(3)*b(2)-a(2)*b(3))*(b(2)*delx-b(1)*!!!!!dely)
         !r_c = r_c/((a(1)*b(2)-a(2)*b(1))*(c(3)*b(2)-c(2)*b(3)) - (a(3)*b(2)-a(2)*b(3))*(c(1)*b(2)-c(2)*b(1)))

         !r_a = b(2)*delx-b(1)*dely - (c(1)*b(2)-c(2)*b(1))*r_c
         !r_a = r_a/(a(1)*b(2)-a(2)*b(1))
         !r_b = dely- r_a*a(2) - r_c*c(2)
         !r_b = r_b/b(2)

        !ina = anint(r_a)
        !inb = anint(r_b)
        !inc = anint(r_c)

       r1(1)=x(1,angle(1,i))-x(1,angle(2,i))
       !r1(1)=r1(1)- ina*a(1) - inb*b(1) - inc*c(1)
       r1(2)=x(2,angle(1,i))-x(2,angle(2,i))
       !r1(2)=r1(2)- ina*a(2) - inb*b(2) - inc*c(2)
       r1(3)=x(3,angle(1,i))-x(3,angle(2,i))
       !r1(3)=r1(3)- ina*a(2) - inb*b(2) - inc*c(2)

       r2(1)=x(1,angle(3,i))-x(1,angle(2,i))
       !r2(1)=r2(1)- ina*a(1) - inb*b(1) - inc*c(1)
       r2(2)=x(2,angle(3,i))-x(2,angle(2,i))
       !r2(2)=r2(2)- ina*a(2) - inb*b(2) - inc*c(2)
       r2(3)=x(3,angle(3,i))-x(3,angle(2,i))
       !r2(3)=r2(3)- ina*a(2) - inb*b(2) - inc*c(2)

       rsq1= r1(1)**2+r1(2)**2+r1(3)**2
       rsq2= r2(1)**2+r2(2)**2+r2(3)**2
       radi= sqrt(rsq1*rsq2)

       cos_ang=r1(1)*r2(1)+r1(2)*r2(2)+r1(3)*r2(3)
       cos_ang=cos_ang/radi
       ang    = acos(cos_ang)
       ave_ang=ave_ang+ang
       ang    = 180.0*ang/pi
       write(32,150)i,ang
!       write(31,400)'harm  ',(angle(j,i),j=1,3),kcth,119.66368
    enddo

    ave_ang=ave_ang/n_ang
    ave_ang=ave_ang*180.0/pi

    thet= ave_ang
    do i=1,n_ang
       write(31,400)'harm  ',(angle(j,i),j=1,3),kcth,thet
    enddo

    print *, 'average angle value:',ave_ang
    !print 110,'dihedral term are not implicit ...'
    write(31,200)'dihedrals',n_dih

     kdih = 0.0
     dih = 30.3340
     
     do i=1,n_dih
        write(31,500)'harm  ',(dihedral(j,i),j=1,4),kdih,dih
     enddo

100 format(A)
!110 format(2X,A)
150 format(I6,F8.3)
200 format(A7,1X,I8)
300 format(A6,2I6,2E16.8)
400 format(A6,3I6,2E16.8)
500 format(A6,4I6,2E16.8)

    close(31)
    close(32)
    close(33)
    return
end


